// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-base-api.proto

package net.rossonet.ptalk.base.grpc;

/**
 * Protobuf type {@code base.HealthRequest}
 */
public final class HealthRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:base.HealthRequest)
    HealthRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HealthRequest.newBuilder() to construct.
  private HealthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HealthRequest() {
    flowReference_ = "";
    unitUniqueName_ = "";
    jsonHardwareInfo_ = "";
    status_ = 0;
    lifecycleStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HealthRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rossonet.ptalk.base.grpc.PtalkBaseObject.internal_static_base_HealthRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rossonet.ptalk.base.grpc.PtalkBaseObject.internal_static_base_HealthRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rossonet.ptalk.base.grpc.HealthRequest.class, net.rossonet.ptalk.base.grpc.HealthRequest.Builder.class);
  }

  public static final int FLOWREFERENCE_FIELD_NUMBER = 1;
  private volatile java.lang.Object flowReference_;
  /**
   * <code>string flowReference = 1;</code>
   * @return The flowReference.
   */
  @java.lang.Override
  public java.lang.String getFlowReference() {
    java.lang.Object ref = flowReference_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flowReference_ = s;
      return s;
    }
  }
  /**
   * <code>string flowReference = 1;</code>
   * @return The bytes for flowReference.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFlowReferenceBytes() {
    java.lang.Object ref = flowReference_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flowReference_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNITUNIQUENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object unitUniqueName_;
  /**
   * <code>string unitUniqueName = 2;</code>
   * @return The unitUniqueName.
   */
  @java.lang.Override
  public java.lang.String getUnitUniqueName() {
    java.lang.Object ref = unitUniqueName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unitUniqueName_ = s;
      return s;
    }
  }
  /**
   * <code>string unitUniqueName = 2;</code>
   * @return The bytes for unitUniqueName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitUniqueNameBytes() {
    java.lang.Object ref = unitUniqueName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unitUniqueName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONHARDWAREINFO_FIELD_NUMBER = 3;
  private volatile java.lang.Object jsonHardwareInfo_;
  /**
   * <code>string jsonHardwareInfo = 3;</code>
   * @return The jsonHardwareInfo.
   */
  @java.lang.Override
  public java.lang.String getJsonHardwareInfo() {
    java.lang.Object ref = jsonHardwareInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonHardwareInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string jsonHardwareInfo = 3;</code>
   * @return The bytes for jsonHardwareInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonHardwareInfoBytes() {
    java.lang.Object ref = jsonHardwareInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonHardwareInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <code>.base.StatusValue status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.base.StatusValue status = 4;</code>
   * @return The status.
   */
  @java.lang.Override public net.rossonet.ptalk.base.grpc.StatusValue getStatus() {
    @SuppressWarnings("deprecation")
    net.rossonet.ptalk.base.grpc.StatusValue result = net.rossonet.ptalk.base.grpc.StatusValue.valueOf(status_);
    return result == null ? net.rossonet.ptalk.base.grpc.StatusValue.UNRECOGNIZED : result;
  }

  public static final int LIFECYCLESTATUS_FIELD_NUMBER = 5;
  private int lifecycleStatus_;
  /**
   * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
   * @return The enum numeric value on the wire for lifecycleStatus.
   */
  @java.lang.Override public int getLifecycleStatusValue() {
    return lifecycleStatus_;
  }
  /**
   * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
   * @return The lifecycleStatus.
   */
  @java.lang.Override public net.rossonet.ptalk.base.grpc.LifecycleStatus getLifecycleStatus() {
    @SuppressWarnings("deprecation")
    net.rossonet.ptalk.base.grpc.LifecycleStatus result = net.rossonet.ptalk.base.grpc.LifecycleStatus.valueOf(lifecycleStatus_);
    return result == null ? net.rossonet.ptalk.base.grpc.LifecycleStatus.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private net.rossonet.ptalk.base.grpc.Timestamp timestamp_;
  /**
   * <code>.base.Timestamp timestamp = 6;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.base.Timestamp timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public net.rossonet.ptalk.base.grpc.Timestamp getTimestamp() {
    return timestamp_ == null ? net.rossonet.ptalk.base.grpc.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.base.Timestamp timestamp = 6;</code>
   */
  @java.lang.Override
  public net.rossonet.ptalk.base.grpc.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flowReference_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, flowReference_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unitUniqueName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, unitUniqueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonHardwareInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonHardwareInfo_);
    }
    if (status_ != net.rossonet.ptalk.base.grpc.StatusValue.STATUS_GOOD.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (lifecycleStatus_ != net.rossonet.ptalk.base.grpc.LifecycleStatus.INIT.getNumber()) {
      output.writeEnum(5, lifecycleStatus_);
    }
    if (timestamp_ != null) {
      output.writeMessage(6, getTimestamp());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flowReference_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, flowReference_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unitUniqueName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, unitUniqueName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonHardwareInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonHardwareInfo_);
    }
    if (status_ != net.rossonet.ptalk.base.grpc.StatusValue.STATUS_GOOD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (lifecycleStatus_ != net.rossonet.ptalk.base.grpc.LifecycleStatus.INIT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, lifecycleStatus_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTimestamp());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rossonet.ptalk.base.grpc.HealthRequest)) {
      return super.equals(obj);
    }
    net.rossonet.ptalk.base.grpc.HealthRequest other = (net.rossonet.ptalk.base.grpc.HealthRequest) obj;

    if (!getFlowReference()
        .equals(other.getFlowReference())) return false;
    if (!getUnitUniqueName()
        .equals(other.getUnitUniqueName())) return false;
    if (!getJsonHardwareInfo()
        .equals(other.getJsonHardwareInfo())) return false;
    if (status_ != other.status_) return false;
    if (lifecycleStatus_ != other.lifecycleStatus_) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FLOWREFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getFlowReference().hashCode();
    hash = (37 * hash) + UNITUNIQUENAME_FIELD_NUMBER;
    hash = (53 * hash) + getUnitUniqueName().hashCode();
    hash = (37 * hash) + JSONHARDWAREINFO_FIELD_NUMBER;
    hash = (53 * hash) + getJsonHardwareInfo().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + LIFECYCLESTATUS_FIELD_NUMBER;
    hash = (53 * hash) + lifecycleStatus_;
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.base.grpc.HealthRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rossonet.ptalk.base.grpc.HealthRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code base.HealthRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:base.HealthRequest)
      net.rossonet.ptalk.base.grpc.HealthRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rossonet.ptalk.base.grpc.PtalkBaseObject.internal_static_base_HealthRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rossonet.ptalk.base.grpc.PtalkBaseObject.internal_static_base_HealthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rossonet.ptalk.base.grpc.HealthRequest.class, net.rossonet.ptalk.base.grpc.HealthRequest.Builder.class);
    }

    // Construct using net.rossonet.ptalk.base.grpc.HealthRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      flowReference_ = "";

      unitUniqueName_ = "";

      jsonHardwareInfo_ = "";

      status_ = 0;

      lifecycleStatus_ = 0;

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rossonet.ptalk.base.grpc.PtalkBaseObject.internal_static_base_HealthRequest_descriptor;
    }

    @java.lang.Override
    public net.rossonet.ptalk.base.grpc.HealthRequest getDefaultInstanceForType() {
      return net.rossonet.ptalk.base.grpc.HealthRequest.getDefaultInstance();
    }

    @java.lang.Override
    public net.rossonet.ptalk.base.grpc.HealthRequest build() {
      net.rossonet.ptalk.base.grpc.HealthRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rossonet.ptalk.base.grpc.HealthRequest buildPartial() {
      net.rossonet.ptalk.base.grpc.HealthRequest result = new net.rossonet.ptalk.base.grpc.HealthRequest(this);
      result.flowReference_ = flowReference_;
      result.unitUniqueName_ = unitUniqueName_;
      result.jsonHardwareInfo_ = jsonHardwareInfo_;
      result.status_ = status_;
      result.lifecycleStatus_ = lifecycleStatus_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rossonet.ptalk.base.grpc.HealthRequest) {
        return mergeFrom((net.rossonet.ptalk.base.grpc.HealthRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rossonet.ptalk.base.grpc.HealthRequest other) {
      if (other == net.rossonet.ptalk.base.grpc.HealthRequest.getDefaultInstance()) return this;
      if (!other.getFlowReference().isEmpty()) {
        flowReference_ = other.flowReference_;
        onChanged();
      }
      if (!other.getUnitUniqueName().isEmpty()) {
        unitUniqueName_ = other.unitUniqueName_;
        onChanged();
      }
      if (!other.getJsonHardwareInfo().isEmpty()) {
        jsonHardwareInfo_ = other.jsonHardwareInfo_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.lifecycleStatus_ != 0) {
        setLifecycleStatusValue(other.getLifecycleStatusValue());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              flowReference_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              unitUniqueName_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              jsonHardwareInfo_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 32: {
              status_ = input.readEnum();

              break;
            } // case 32
            case 40: {
              lifecycleStatus_ = input.readEnum();

              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object flowReference_ = "";
    /**
     * <code>string flowReference = 1;</code>
     * @return The flowReference.
     */
    public java.lang.String getFlowReference() {
      java.lang.Object ref = flowReference_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flowReference_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string flowReference = 1;</code>
     * @return The bytes for flowReference.
     */
    public com.google.protobuf.ByteString
        getFlowReferenceBytes() {
      java.lang.Object ref = flowReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flowReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string flowReference = 1;</code>
     * @param value The flowReference to set.
     * @return This builder for chaining.
     */
    public Builder setFlowReference(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      flowReference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string flowReference = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlowReference() {
      
      flowReference_ = getDefaultInstance().getFlowReference();
      onChanged();
      return this;
    }
    /**
     * <code>string flowReference = 1;</code>
     * @param value The bytes for flowReference to set.
     * @return This builder for chaining.
     */
    public Builder setFlowReferenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      flowReference_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object unitUniqueName_ = "";
    /**
     * <code>string unitUniqueName = 2;</code>
     * @return The unitUniqueName.
     */
    public java.lang.String getUnitUniqueName() {
      java.lang.Object ref = unitUniqueName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unitUniqueName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string unitUniqueName = 2;</code>
     * @return The bytes for unitUniqueName.
     */
    public com.google.protobuf.ByteString
        getUnitUniqueNameBytes() {
      java.lang.Object ref = unitUniqueName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unitUniqueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string unitUniqueName = 2;</code>
     * @param value The unitUniqueName to set.
     * @return This builder for chaining.
     */
    public Builder setUnitUniqueName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unitUniqueName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string unitUniqueName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitUniqueName() {
      
      unitUniqueName_ = getDefaultInstance().getUnitUniqueName();
      onChanged();
      return this;
    }
    /**
     * <code>string unitUniqueName = 2;</code>
     * @param value The bytes for unitUniqueName to set.
     * @return This builder for chaining.
     */
    public Builder setUnitUniqueNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unitUniqueName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jsonHardwareInfo_ = "";
    /**
     * <code>string jsonHardwareInfo = 3;</code>
     * @return The jsonHardwareInfo.
     */
    public java.lang.String getJsonHardwareInfo() {
      java.lang.Object ref = jsonHardwareInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonHardwareInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jsonHardwareInfo = 3;</code>
     * @return The bytes for jsonHardwareInfo.
     */
    public com.google.protobuf.ByteString
        getJsonHardwareInfoBytes() {
      java.lang.Object ref = jsonHardwareInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonHardwareInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jsonHardwareInfo = 3;</code>
     * @param value The jsonHardwareInfo to set.
     * @return This builder for chaining.
     */
    public Builder setJsonHardwareInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jsonHardwareInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jsonHardwareInfo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonHardwareInfo() {
      
      jsonHardwareInfo_ = getDefaultInstance().getJsonHardwareInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string jsonHardwareInfo = 3;</code>
     * @param value The bytes for jsonHardwareInfo to set.
     * @return This builder for chaining.
     */
    public Builder setJsonHardwareInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jsonHardwareInfo_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.base.StatusValue status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.base.StatusValue status = 4;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.base.StatusValue status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public net.rossonet.ptalk.base.grpc.StatusValue getStatus() {
      @SuppressWarnings("deprecation")
      net.rossonet.ptalk.base.grpc.StatusValue result = net.rossonet.ptalk.base.grpc.StatusValue.valueOf(status_);
      return result == null ? net.rossonet.ptalk.base.grpc.StatusValue.UNRECOGNIZED : result;
    }
    /**
     * <code>.base.StatusValue status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(net.rossonet.ptalk.base.grpc.StatusValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.base.StatusValue status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int lifecycleStatus_ = 0;
    /**
     * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
     * @return The enum numeric value on the wire for lifecycleStatus.
     */
    @java.lang.Override public int getLifecycleStatusValue() {
      return lifecycleStatus_;
    }
    /**
     * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
     * @param value The enum numeric value on the wire for lifecycleStatus to set.
     * @return This builder for chaining.
     */
    public Builder setLifecycleStatusValue(int value) {
      
      lifecycleStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
     * @return The lifecycleStatus.
     */
    @java.lang.Override
    public net.rossonet.ptalk.base.grpc.LifecycleStatus getLifecycleStatus() {
      @SuppressWarnings("deprecation")
      net.rossonet.ptalk.base.grpc.LifecycleStatus result = net.rossonet.ptalk.base.grpc.LifecycleStatus.valueOf(lifecycleStatus_);
      return result == null ? net.rossonet.ptalk.base.grpc.LifecycleStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
     * @param value The lifecycleStatus to set.
     * @return This builder for chaining.
     */
    public Builder setLifecycleStatus(net.rossonet.ptalk.base.grpc.LifecycleStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      lifecycleStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.base.LifecycleStatus lifecycleStatus = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLifecycleStatus() {
      
      lifecycleStatus_ = 0;
      onChanged();
      return this;
    }

    private net.rossonet.ptalk.base.grpc.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.rossonet.ptalk.base.grpc.Timestamp, net.rossonet.ptalk.base.grpc.Timestamp.Builder, net.rossonet.ptalk.base.grpc.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     * @return The timestamp.
     */
    public net.rossonet.ptalk.base.grpc.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? net.rossonet.ptalk.base.grpc.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(net.rossonet.ptalk.base.grpc.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(
        net.rossonet.ptalk.base.grpc.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    public Builder mergeTimestamp(net.rossonet.ptalk.base.grpc.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            net.rossonet.ptalk.base.grpc.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    public net.rossonet.ptalk.base.grpc.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    public net.rossonet.ptalk.base.grpc.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            net.rossonet.ptalk.base.grpc.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.base.Timestamp timestamp = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.rossonet.ptalk.base.grpc.Timestamp, net.rossonet.ptalk.base.grpc.Timestamp.Builder, net.rossonet.ptalk.base.grpc.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.rossonet.ptalk.base.grpc.Timestamp, net.rossonet.ptalk.base.grpc.Timestamp.Builder, net.rossonet.ptalk.base.grpc.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:base.HealthRequest)
  }

  // @@protoc_insertion_point(class_scope:base.HealthRequest)
  private static final net.rossonet.ptalk.base.grpc.HealthRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rossonet.ptalk.base.grpc.HealthRequest();
  }

  public static net.rossonet.ptalk.base.grpc.HealthRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HealthRequest>
      PARSER = new com.google.protobuf.AbstractParser<HealthRequest>() {
    @java.lang.Override
    public HealthRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HealthRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HealthRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rossonet.ptalk.base.grpc.HealthRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

