// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-nlu-api.proto

package net.rossonet.ptalk.grpc;

public interface ListCommandsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.ListCommandsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.beacon.Agent agentTarget = 1;</code>
   * @return Whether the agentTarget field is set.
   */
  boolean hasAgentTarget();
  /**
   * <code>.beacon.Agent agentTarget = 1;</code>
   * @return The agentTarget.
   */
  net.rossonet.ptalk.grpc.Agent getAgentTarget();
  /**
   * <code>.beacon.Agent agentTarget = 1;</code>
   */
  net.rossonet.ptalk.grpc.AgentOrBuilder getAgentTargetOrBuilder();

  /**
   * <code>.beacon.Agent agentSender = 2;</code>
   * @return Whether the agentSender field is set.
   */
  boolean hasAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 2;</code>
   * @return The agentSender.
   */
  net.rossonet.ptalk.grpc.Agent getAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 2;</code>
   */
  net.rossonet.ptalk.grpc.AgentOrBuilder getAgentSenderOrBuilder();
}
