// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-nlu-api.proto

package net.rossonet.ptalk.nlu.grpc;

/**
 * <pre>
 * any nlu agent can have many models, to better identify this models
 * </pre>
 *
 * Protobuf type {@code nlu.NluModel}
 */
public final class NluModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nlu.NluModel)
    NluModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NluModel.newBuilder() to construct.
  private NluModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NluModel() {
    requiredCapability_ = "";
    model_ = "";
    modelVersion_ = "";
    jsonModelSignature_ = "";
    inputExample_ = "";
    outputExample_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NluModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rossonet.ptalk.nlu.grpc.PtalkNluApi.internal_static_nlu_NluModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rossonet.ptalk.nlu.grpc.PtalkNluApi.internal_static_nlu_NluModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rossonet.ptalk.nlu.grpc.NluModel.class, net.rossonet.ptalk.nlu.grpc.NluModel.Builder.class);
  }

  public static final int REQUIREDCAPABILITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object requiredCapability_;
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>string requiredCapability = 1;</code>
   * @return The requiredCapability.
   */
  @java.lang.Override
  public java.lang.String getRequiredCapability() {
    java.lang.Object ref = requiredCapability_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requiredCapability_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional
   * </pre>
   *
   * <code>string requiredCapability = 1;</code>
   * @return The bytes for requiredCapability.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequiredCapabilityBytes() {
    java.lang.Object ref = requiredCapability_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requiredCapability_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object model_;
  /**
   * <pre>
   * unique name of the model
   * </pre>
   *
   * <code>string model = 2;</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * unique name of the model
   * </pre>
   *
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODELVERSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object modelVersion_;
  /**
   * <pre>
   * version of the model, this field can be used to call different version on the same agent
   * </pre>
   *
   * <code>string modelVersion = 3;</code>
   * @return The modelVersion.
   */
  @java.lang.Override
  public java.lang.String getModelVersion() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * version of the model, this field can be used to call different version on the same agent
   * </pre>
   *
   * <code>string modelVersion = 3;</code>
   * @return The bytes for modelVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelVersionBytes() {
    java.lang.Object ref = modelVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONMODELSIGNATURE_FIELD_NUMBER = 4;
  private volatile java.lang.Object jsonModelSignature_;
  /**
   * <pre>
   * description of a model’s inputs and outputs
   * </pre>
   *
   * <code>string jsonModelSignature = 4;</code>
   * @return The jsonModelSignature.
   */
  @java.lang.Override
  public java.lang.String getJsonModelSignature() {
    java.lang.Object ref = jsonModelSignature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonModelSignature_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * description of a model’s inputs and outputs
   * </pre>
   *
   * <code>string jsonModelSignature = 4;</code>
   * @return The bytes for jsonModelSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonModelSignatureBytes() {
    java.lang.Object ref = jsonModelSignature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonModelSignature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUTEXAMPLE_FIELD_NUMBER = 5;
  private volatile java.lang.Object inputExample_;
  /**
   * <pre>
   * example of a valid model input
   * </pre>
   *
   * <code>string inputExample = 5;</code>
   * @return The inputExample.
   */
  @java.lang.Override
  public java.lang.String getInputExample() {
    java.lang.Object ref = inputExample_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inputExample_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * example of a valid model input
   * </pre>
   *
   * <code>string inputExample = 5;</code>
   * @return The bytes for inputExample.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputExampleBytes() {
    java.lang.Object ref = inputExample_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inputExample_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUTEXAMPLE_FIELD_NUMBER = 6;
  private volatile java.lang.Object outputExample_;
  /**
   * <pre>
   * example of a valid model output
   * </pre>
   *
   * <code>string outputExample = 6;</code>
   * @return The outputExample.
   */
  @java.lang.Override
  public java.lang.String getOutputExample() {
    java.lang.Object ref = outputExample_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputExample_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * example of a valid model output
   * </pre>
   *
   * <code>string outputExample = 6;</code>
   * @return The bytes for outputExample.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutputExampleBytes() {
    java.lang.Object ref = outputExample_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputExample_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requiredCapability_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requiredCapability_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, model_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, modelVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonModelSignature_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, jsonModelSignature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inputExample_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, inputExample_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outputExample_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, outputExample_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requiredCapability_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requiredCapability_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, model_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, modelVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonModelSignature_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, jsonModelSignature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inputExample_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, inputExample_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outputExample_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, outputExample_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rossonet.ptalk.nlu.grpc.NluModel)) {
      return super.equals(obj);
    }
    net.rossonet.ptalk.nlu.grpc.NluModel other = (net.rossonet.ptalk.nlu.grpc.NluModel) obj;

    if (!getRequiredCapability()
        .equals(other.getRequiredCapability())) return false;
    if (!getModel()
        .equals(other.getModel())) return false;
    if (!getModelVersion()
        .equals(other.getModelVersion())) return false;
    if (!getJsonModelSignature()
        .equals(other.getJsonModelSignature())) return false;
    if (!getInputExample()
        .equals(other.getInputExample())) return false;
    if (!getOutputExample()
        .equals(other.getOutputExample())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUIREDCAPABILITY_FIELD_NUMBER;
    hash = (53 * hash) + getRequiredCapability().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + MODELVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getModelVersion().hashCode();
    hash = (37 * hash) + JSONMODELSIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getJsonModelSignature().hashCode();
    hash = (37 * hash) + INPUTEXAMPLE_FIELD_NUMBER;
    hash = (53 * hash) + getInputExample().hashCode();
    hash = (37 * hash) + OUTPUTEXAMPLE_FIELD_NUMBER;
    hash = (53 * hash) + getOutputExample().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.nlu.grpc.NluModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rossonet.ptalk.nlu.grpc.NluModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * any nlu agent can have many models, to better identify this models
   * </pre>
   *
   * Protobuf type {@code nlu.NluModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nlu.NluModel)
      net.rossonet.ptalk.nlu.grpc.NluModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rossonet.ptalk.nlu.grpc.PtalkNluApi.internal_static_nlu_NluModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rossonet.ptalk.nlu.grpc.PtalkNluApi.internal_static_nlu_NluModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rossonet.ptalk.nlu.grpc.NluModel.class, net.rossonet.ptalk.nlu.grpc.NluModel.Builder.class);
    }

    // Construct using net.rossonet.ptalk.nlu.grpc.NluModel.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requiredCapability_ = "";

      model_ = "";

      modelVersion_ = "";

      jsonModelSignature_ = "";

      inputExample_ = "";

      outputExample_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rossonet.ptalk.nlu.grpc.PtalkNluApi.internal_static_nlu_NluModel_descriptor;
    }

    @java.lang.Override
    public net.rossonet.ptalk.nlu.grpc.NluModel getDefaultInstanceForType() {
      return net.rossonet.ptalk.nlu.grpc.NluModel.getDefaultInstance();
    }

    @java.lang.Override
    public net.rossonet.ptalk.nlu.grpc.NluModel build() {
      net.rossonet.ptalk.nlu.grpc.NluModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rossonet.ptalk.nlu.grpc.NluModel buildPartial() {
      net.rossonet.ptalk.nlu.grpc.NluModel result = new net.rossonet.ptalk.nlu.grpc.NluModel(this);
      result.requiredCapability_ = requiredCapability_;
      result.model_ = model_;
      result.modelVersion_ = modelVersion_;
      result.jsonModelSignature_ = jsonModelSignature_;
      result.inputExample_ = inputExample_;
      result.outputExample_ = outputExample_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rossonet.ptalk.nlu.grpc.NluModel) {
        return mergeFrom((net.rossonet.ptalk.nlu.grpc.NluModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rossonet.ptalk.nlu.grpc.NluModel other) {
      if (other == net.rossonet.ptalk.nlu.grpc.NluModel.getDefaultInstance()) return this;
      if (!other.getRequiredCapability().isEmpty()) {
        requiredCapability_ = other.requiredCapability_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (!other.getModelVersion().isEmpty()) {
        modelVersion_ = other.modelVersion_;
        onChanged();
      }
      if (!other.getJsonModelSignature().isEmpty()) {
        jsonModelSignature_ = other.jsonModelSignature_;
        onChanged();
      }
      if (!other.getInputExample().isEmpty()) {
        inputExample_ = other.inputExample_;
        onChanged();
      }
      if (!other.getOutputExample().isEmpty()) {
        outputExample_ = other.outputExample_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              requiredCapability_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              model_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              modelVersion_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              jsonModelSignature_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              inputExample_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              outputExample_ = input.readStringRequireUtf8();

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object requiredCapability_ = "";
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string requiredCapability = 1;</code>
     * @return The requiredCapability.
     */
    public java.lang.String getRequiredCapability() {
      java.lang.Object ref = requiredCapability_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requiredCapability_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string requiredCapability = 1;</code>
     * @return The bytes for requiredCapability.
     */
    public com.google.protobuf.ByteString
        getRequiredCapabilityBytes() {
      java.lang.Object ref = requiredCapability_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requiredCapability_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string requiredCapability = 1;</code>
     * @param value The requiredCapability to set.
     * @return This builder for chaining.
     */
    public Builder setRequiredCapability(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requiredCapability_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string requiredCapability = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequiredCapability() {
      
      requiredCapability_ = getDefaultInstance().getRequiredCapability();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional
     * </pre>
     *
     * <code>string requiredCapability = 1;</code>
     * @param value The bytes for requiredCapability to set.
     * @return This builder for chaining.
     */
    public Builder setRequiredCapabilityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requiredCapability_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <pre>
     * unique name of the model
     * </pre>
     *
     * <code>string model = 2;</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * unique name of the model
     * </pre>
     *
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * unique name of the model
     * </pre>
     *
     * <code>string model = 2;</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique name of the model
     * </pre>
     *
     * <code>string model = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unique name of the model
     * </pre>
     *
     * <code>string model = 2;</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object modelVersion_ = "";
    /**
     * <pre>
     * version of the model, this field can be used to call different version on the same agent
     * </pre>
     *
     * <code>string modelVersion = 3;</code>
     * @return The modelVersion.
     */
    public java.lang.String getModelVersion() {
      java.lang.Object ref = modelVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * version of the model, this field can be used to call different version on the same agent
     * </pre>
     *
     * <code>string modelVersion = 3;</code>
     * @return The bytes for modelVersion.
     */
    public com.google.protobuf.ByteString
        getModelVersionBytes() {
      java.lang.Object ref = modelVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * version of the model, this field can be used to call different version on the same agent
     * </pre>
     *
     * <code>string modelVersion = 3;</code>
     * @param value The modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * version of the model, this field can be used to call different version on the same agent
     * </pre>
     *
     * <code>string modelVersion = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelVersion() {
      
      modelVersion_ = getDefaultInstance().getModelVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * version of the model, this field can be used to call different version on the same agent
     * </pre>
     *
     * <code>string modelVersion = 3;</code>
     * @param value The bytes for modelVersion to set.
     * @return This builder for chaining.
     */
    public Builder setModelVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jsonModelSignature_ = "";
    /**
     * <pre>
     * description of a model’s inputs and outputs
     * </pre>
     *
     * <code>string jsonModelSignature = 4;</code>
     * @return The jsonModelSignature.
     */
    public java.lang.String getJsonModelSignature() {
      java.lang.Object ref = jsonModelSignature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonModelSignature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * description of a model’s inputs and outputs
     * </pre>
     *
     * <code>string jsonModelSignature = 4;</code>
     * @return The bytes for jsonModelSignature.
     */
    public com.google.protobuf.ByteString
        getJsonModelSignatureBytes() {
      java.lang.Object ref = jsonModelSignature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonModelSignature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * description of a model’s inputs and outputs
     * </pre>
     *
     * <code>string jsonModelSignature = 4;</code>
     * @param value The jsonModelSignature to set.
     * @return This builder for chaining.
     */
    public Builder setJsonModelSignature(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jsonModelSignature_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * description of a model’s inputs and outputs
     * </pre>
     *
     * <code>string jsonModelSignature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonModelSignature() {
      
      jsonModelSignature_ = getDefaultInstance().getJsonModelSignature();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * description of a model’s inputs and outputs
     * </pre>
     *
     * <code>string jsonModelSignature = 4;</code>
     * @param value The bytes for jsonModelSignature to set.
     * @return This builder for chaining.
     */
    public Builder setJsonModelSignatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jsonModelSignature_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inputExample_ = "";
    /**
     * <pre>
     * example of a valid model input
     * </pre>
     *
     * <code>string inputExample = 5;</code>
     * @return The inputExample.
     */
    public java.lang.String getInputExample() {
      java.lang.Object ref = inputExample_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inputExample_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * example of a valid model input
     * </pre>
     *
     * <code>string inputExample = 5;</code>
     * @return The bytes for inputExample.
     */
    public com.google.protobuf.ByteString
        getInputExampleBytes() {
      java.lang.Object ref = inputExample_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputExample_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * example of a valid model input
     * </pre>
     *
     * <code>string inputExample = 5;</code>
     * @param value The inputExample to set.
     * @return This builder for chaining.
     */
    public Builder setInputExample(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inputExample_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * example of a valid model input
     * </pre>
     *
     * <code>string inputExample = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputExample() {
      
      inputExample_ = getDefaultInstance().getInputExample();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * example of a valid model input
     * </pre>
     *
     * <code>string inputExample = 5;</code>
     * @param value The bytes for inputExample to set.
     * @return This builder for chaining.
     */
    public Builder setInputExampleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inputExample_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object outputExample_ = "";
    /**
     * <pre>
     * example of a valid model output
     * </pre>
     *
     * <code>string outputExample = 6;</code>
     * @return The outputExample.
     */
    public java.lang.String getOutputExample() {
      java.lang.Object ref = outputExample_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputExample_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * example of a valid model output
     * </pre>
     *
     * <code>string outputExample = 6;</code>
     * @return The bytes for outputExample.
     */
    public com.google.protobuf.ByteString
        getOutputExampleBytes() {
      java.lang.Object ref = outputExample_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputExample_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * example of a valid model output
     * </pre>
     *
     * <code>string outputExample = 6;</code>
     * @param value The outputExample to set.
     * @return This builder for chaining.
     */
    public Builder setOutputExample(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outputExample_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * example of a valid model output
     * </pre>
     *
     * <code>string outputExample = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputExample() {
      
      outputExample_ = getDefaultInstance().getOutputExample();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * example of a valid model output
     * </pre>
     *
     * <code>string outputExample = 6;</code>
     * @param value The bytes for outputExample to set.
     * @return This builder for chaining.
     */
    public Builder setOutputExampleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outputExample_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nlu.NluModel)
  }

  // @@protoc_insertion_point(class_scope:nlu.NluModel)
  private static final net.rossonet.ptalk.nlu.grpc.NluModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rossonet.ptalk.nlu.grpc.NluModel();
  }

  public static net.rossonet.ptalk.nlu.grpc.NluModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NluModel>
      PARSER = new com.google.protobuf.AbstractParser<NluModel>() {
    @java.lang.Override
    public NluModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NluModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NluModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rossonet.ptalk.nlu.grpc.NluModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

