// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-nlu-api.proto

package net.rossonet.ptalk.nlu.grpc;

public interface NluTrainingModelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nlu.NluTrainingModelRequest)
    com.google.protobuf.MessageOrBuilder {
}
