// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-base-api.proto

package net.rossonet.ptalk.base.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:base.Empty)
    com.google.protobuf.MessageOrBuilder {
}
