// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-nlu-api.proto

package net.rossonet.ptalk.grpc;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   * @return Whether the agentSender field is set.
   */
  boolean hasAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   * @return The agentSender.
   */
  net.rossonet.ptalk.grpc.Agent getAgentSender();
  /**
   * <code>.beacon.Agent agentSender = 1;</code>
   */
  net.rossonet.ptalk.grpc.AgentOrBuilder getAgentSenderOrBuilder();

  /**
   * <code>string command = 2;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 2;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
