// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-nlu-api.proto

package net.rossonet.ptalk.grpc;

/**
 * Protobuf type {@code beacon.ConfigReply}
 */
public final class ConfigReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:beacon.ConfigReply)
    ConfigReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfigReply.newBuilder() to construct.
  private ConfigReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfigReply() {
    base64Config_ = "";
    jsonConfig_ = "";
    ymlConfig_ = "";
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConfigReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rossonet.ptalk.grpc.PtaskNluApi.internal_static_beacon_ConfigReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rossonet.ptalk.grpc.PtaskNluApi.internal_static_beacon_ConfigReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rossonet.ptalk.grpc.ConfigReply.class, net.rossonet.ptalk.grpc.ConfigReply.Builder.class);
  }

  public static final int BASE64CONFIG_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object base64Config_ = "";
  /**
   * <code>string base64Config = 1;</code>
   * @return The base64Config.
   */
  @java.lang.Override
  public java.lang.String getBase64Config() {
    java.lang.Object ref = base64Config_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      base64Config_ = s;
      return s;
    }
  }
  /**
   * <code>string base64Config = 1;</code>
   * @return The bytes for base64Config.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBase64ConfigBytes() {
    java.lang.Object ref = base64Config_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      base64Config_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONCONFIG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jsonConfig_ = "";
  /**
   * <code>string jsonConfig = 2;</code>
   * @return The jsonConfig.
   */
  @java.lang.Override
  public java.lang.String getJsonConfig() {
    java.lang.Object ref = jsonConfig_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonConfig_ = s;
      return s;
    }
  }
  /**
   * <code>string jsonConfig = 2;</code>
   * @return The bytes for jsonConfig.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonConfigBytes() {
    java.lang.Object ref = jsonConfig_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonConfig_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YMLCONFIG_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ymlConfig_ = "";
  /**
   * <code>string ymlConfig = 3;</code>
   * @return The ymlConfig.
   */
  @java.lang.Override
  public java.lang.String getYmlConfig() {
    java.lang.Object ref = ymlConfig_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ymlConfig_ = s;
      return s;
    }
  }
  /**
   * <code>string ymlConfig = 3;</code>
   * @return The bytes for ymlConfig.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getYmlConfigBytes() {
    java.lang.Object ref = ymlConfig_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ymlConfig_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESTARTAT_FIELD_NUMBER = 4;
  private long restartAt_ = 0L;
  /**
   * <code>int64 restartAt = 4;</code>
   * @return The restartAt.
   */
  @java.lang.Override
  public long getRestartAt() {
    return restartAt_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_ = 0;
  /**
   * <code>.beacon.StatusValue status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.beacon.StatusValue status = 5;</code>
   * @return The status.
   */
  @java.lang.Override public net.rossonet.ptalk.grpc.StatusValue getStatus() {
    net.rossonet.ptalk.grpc.StatusValue result = net.rossonet.ptalk.grpc.StatusValue.forNumber(status_);
    return result == null ? net.rossonet.ptalk.grpc.StatusValue.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(base64Config_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, base64Config_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonConfig_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jsonConfig_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ymlConfig_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ymlConfig_);
    }
    if (restartAt_ != 0L) {
      output.writeInt64(4, restartAt_);
    }
    if (status_ != net.rossonet.ptalk.grpc.StatusValue.GOOD.getNumber()) {
      output.writeEnum(5, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(base64Config_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, base64Config_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonConfig_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jsonConfig_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ymlConfig_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ymlConfig_);
    }
    if (restartAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, restartAt_);
    }
    if (status_ != net.rossonet.ptalk.grpc.StatusValue.GOOD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rossonet.ptalk.grpc.ConfigReply)) {
      return super.equals(obj);
    }
    net.rossonet.ptalk.grpc.ConfigReply other = (net.rossonet.ptalk.grpc.ConfigReply) obj;

    if (!getBase64Config()
        .equals(other.getBase64Config())) return false;
    if (!getJsonConfig()
        .equals(other.getJsonConfig())) return false;
    if (!getYmlConfig()
        .equals(other.getYmlConfig())) return false;
    if (getRestartAt()
        != other.getRestartAt()) return false;
    if (status_ != other.status_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BASE64CONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getBase64Config().hashCode();
    hash = (37 * hash) + JSONCONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getJsonConfig().hashCode();
    hash = (37 * hash) + YMLCONFIG_FIELD_NUMBER;
    hash = (53 * hash) + getYmlConfig().hashCode();
    hash = (37 * hash) + RESTARTAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRestartAt());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.grpc.ConfigReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rossonet.ptalk.grpc.ConfigReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code beacon.ConfigReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:beacon.ConfigReply)
      net.rossonet.ptalk.grpc.ConfigReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rossonet.ptalk.grpc.PtaskNluApi.internal_static_beacon_ConfigReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rossonet.ptalk.grpc.PtaskNluApi.internal_static_beacon_ConfigReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rossonet.ptalk.grpc.ConfigReply.class, net.rossonet.ptalk.grpc.ConfigReply.Builder.class);
    }

    // Construct using net.rossonet.ptalk.grpc.ConfigReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base64Config_ = "";
      jsonConfig_ = "";
      ymlConfig_ = "";
      restartAt_ = 0L;
      status_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rossonet.ptalk.grpc.PtaskNluApi.internal_static_beacon_ConfigReply_descriptor;
    }

    @java.lang.Override
    public net.rossonet.ptalk.grpc.ConfigReply getDefaultInstanceForType() {
      return net.rossonet.ptalk.grpc.ConfigReply.getDefaultInstance();
    }

    @java.lang.Override
    public net.rossonet.ptalk.grpc.ConfigReply build() {
      net.rossonet.ptalk.grpc.ConfigReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rossonet.ptalk.grpc.ConfigReply buildPartial() {
      net.rossonet.ptalk.grpc.ConfigReply result = new net.rossonet.ptalk.grpc.ConfigReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.rossonet.ptalk.grpc.ConfigReply result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base64Config_ = base64Config_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.jsonConfig_ = jsonConfig_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ymlConfig_ = ymlConfig_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.restartAt_ = restartAt_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rossonet.ptalk.grpc.ConfigReply) {
        return mergeFrom((net.rossonet.ptalk.grpc.ConfigReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rossonet.ptalk.grpc.ConfigReply other) {
      if (other == net.rossonet.ptalk.grpc.ConfigReply.getDefaultInstance()) return this;
      if (!other.getBase64Config().isEmpty()) {
        base64Config_ = other.base64Config_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getJsonConfig().isEmpty()) {
        jsonConfig_ = other.jsonConfig_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getYmlConfig().isEmpty()) {
        ymlConfig_ = other.ymlConfig_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getRestartAt() != 0L) {
        setRestartAt(other.getRestartAt());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              base64Config_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              jsonConfig_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ymlConfig_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              restartAt_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object base64Config_ = "";
    /**
     * <code>string base64Config = 1;</code>
     * @return The base64Config.
     */
    public java.lang.String getBase64Config() {
      java.lang.Object ref = base64Config_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        base64Config_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string base64Config = 1;</code>
     * @return The bytes for base64Config.
     */
    public com.google.protobuf.ByteString
        getBase64ConfigBytes() {
      java.lang.Object ref = base64Config_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        base64Config_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string base64Config = 1;</code>
     * @param value The base64Config to set.
     * @return This builder for chaining.
     */
    public Builder setBase64Config(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      base64Config_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string base64Config = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBase64Config() {
      base64Config_ = getDefaultInstance().getBase64Config();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string base64Config = 1;</code>
     * @param value The bytes for base64Config to set.
     * @return This builder for chaining.
     */
    public Builder setBase64ConfigBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      base64Config_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object jsonConfig_ = "";
    /**
     * <code>string jsonConfig = 2;</code>
     * @return The jsonConfig.
     */
    public java.lang.String getJsonConfig() {
      java.lang.Object ref = jsonConfig_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonConfig_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jsonConfig = 2;</code>
     * @return The bytes for jsonConfig.
     */
    public com.google.protobuf.ByteString
        getJsonConfigBytes() {
      java.lang.Object ref = jsonConfig_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonConfig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jsonConfig = 2;</code>
     * @param value The jsonConfig to set.
     * @return This builder for chaining.
     */
    public Builder setJsonConfig(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jsonConfig_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string jsonConfig = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonConfig() {
      jsonConfig_ = getDefaultInstance().getJsonConfig();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string jsonConfig = 2;</code>
     * @param value The bytes for jsonConfig to set.
     * @return This builder for chaining.
     */
    public Builder setJsonConfigBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jsonConfig_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ymlConfig_ = "";
    /**
     * <code>string ymlConfig = 3;</code>
     * @return The ymlConfig.
     */
    public java.lang.String getYmlConfig() {
      java.lang.Object ref = ymlConfig_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ymlConfig_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ymlConfig = 3;</code>
     * @return The bytes for ymlConfig.
     */
    public com.google.protobuf.ByteString
        getYmlConfigBytes() {
      java.lang.Object ref = ymlConfig_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ymlConfig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ymlConfig = 3;</code>
     * @param value The ymlConfig to set.
     * @return This builder for chaining.
     */
    public Builder setYmlConfig(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ymlConfig_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string ymlConfig = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearYmlConfig() {
      ymlConfig_ = getDefaultInstance().getYmlConfig();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string ymlConfig = 3;</code>
     * @param value The bytes for ymlConfig to set.
     * @return This builder for chaining.
     */
    public Builder setYmlConfigBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ymlConfig_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long restartAt_ ;
    /**
     * <code>int64 restartAt = 4;</code>
     * @return The restartAt.
     */
    @java.lang.Override
    public long getRestartAt() {
      return restartAt_;
    }
    /**
     * <code>int64 restartAt = 4;</code>
     * @param value The restartAt to set.
     * @return This builder for chaining.
     */
    public Builder setRestartAt(long value) {

      restartAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 restartAt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRestartAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      restartAt_ = 0L;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.beacon.StatusValue status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.beacon.StatusValue status = 5;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.beacon.StatusValue status = 5;</code>
     * @return The status.
     */
    @java.lang.Override
    public net.rossonet.ptalk.grpc.StatusValue getStatus() {
      net.rossonet.ptalk.grpc.StatusValue result = net.rossonet.ptalk.grpc.StatusValue.forNumber(status_);
      return result == null ? net.rossonet.ptalk.grpc.StatusValue.UNRECOGNIZED : result;
    }
    /**
     * <code>.beacon.StatusValue status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(net.rossonet.ptalk.grpc.StatusValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.beacon.StatusValue status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:beacon.ConfigReply)
  }

  // @@protoc_insertion_point(class_scope:beacon.ConfigReply)
  private static final net.rossonet.ptalk.grpc.ConfigReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rossonet.ptalk.grpc.ConfigReply();
  }

  public static net.rossonet.ptalk.grpc.ConfigReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfigReply>
      PARSER = new com.google.protobuf.AbstractParser<ConfigReply>() {
    @java.lang.Override
    public ConfigReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConfigReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfigReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rossonet.ptalk.grpc.ConfigReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

