// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-nlu-api.proto

package net.rossonet.ptalk.grpc;

public interface AgentProxyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:beacon.AgentProxyReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 idProxyRequest = 1;</code>
   * @return The idProxyRequest.
   */
  long getIdProxyRequest();

  /**
   * <code>.beacon.Agent agentSource = 2;</code>
   * @return Whether the agentSource field is set.
   */
  boolean hasAgentSource();
  /**
   * <code>.beacon.Agent agentSource = 2;</code>
   * @return The agentSource.
   */
  net.rossonet.ptalk.grpc.Agent getAgentSource();
  /**
   * <code>.beacon.Agent agentSource = 2;</code>
   */
  net.rossonet.ptalk.grpc.AgentOrBuilder getAgentSourceOrBuilder();

  /**
   * <code>.beacon.Agent agentDestination = 3;</code>
   * @return Whether the agentDestination field is set.
   */
  boolean hasAgentDestination();
  /**
   * <code>.beacon.Agent agentDestination = 3;</code>
   * @return The agentDestination.
   */
  net.rossonet.ptalk.grpc.Agent getAgentDestination();
  /**
   * <code>.beacon.Agent agentDestination = 3;</code>
   */
  net.rossonet.ptalk.grpc.AgentOrBuilder getAgentDestinationOrBuilder();

  /**
   * <code>string srcIp = 4;</code>
   * @return The srcIp.
   */
  java.lang.String getSrcIp();
  /**
   * <code>string srcIp = 4;</code>
   * @return The bytes for srcIp.
   */
  com.google.protobuf.ByteString
      getSrcIpBytes();

  /**
   * <code>int32 srcPort = 5;</code>
   * @return The srcPort.
   */
  int getSrcPort();

  /**
   * <code>string header = 6;</code>
   * @return The header.
   */
  java.lang.String getHeader();
  /**
   * <code>string header = 6;</code>
   * @return The bytes for header.
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <code>string payload = 7;</code>
   * @return The payload.
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 7;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();

  /**
   * <code>.beacon.Status status = 8;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.beacon.Status status = 8;</code>
   * @return The status.
   */
  net.rossonet.ptalk.grpc.Status getStatus();
  /**
   * <code>.beacon.Status status = 8;</code>
   */
  net.rossonet.ptalk.grpc.StatusOrBuilder getStatusOrBuilder();
}
