// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-ability-api.proto

package net.rossonet.ptalk.ability.grpc;

public interface RegisterRulesReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ability.RegisterRulesReply)
    com.google.protobuf.MessageOrBuilder {
}
