// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-ability-api.proto

package net.rossonet.ptalk.ability.grpc;

public interface RuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ability.Rule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ruleUniqueName = 1;</code>
   * @return The ruleUniqueName.
   */
  java.lang.String getRuleUniqueName();
  /**
   * <code>string ruleUniqueName = 1;</code>
   * @return The bytes for ruleUniqueName.
   */
  com.google.protobuf.ByteString
      getRuleUniqueNameBytes();

  /**
   * <code>string task = 2;</code>
   * @return The task.
   */
  java.lang.String getTask();
  /**
   * <code>string task = 2;</code>
   * @return The bytes for task.
   */
  com.google.protobuf.ByteString
      getTaskBytes();
}
