// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface AgentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.AgentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.channelGrpc.RegisterRequest request = 1;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.channelGrpc.RegisterRequest request = 1;</code>
   * @return The request.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.RegisterRequest getRequest();
  /**
   * <code>.channelGrpc.RegisterRequest request = 1;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.RegisterRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>string idRequest = 2;</code>
   * @return The idRequest.
   */
  java.lang.String getIdRequest();
  /**
   * <code>string idRequest = 2;</code>
   * @return The bytes for idRequest.
   */
  com.google.protobuf.ByteString
      getIdRequestBytes();

  /**
   * <code>.channelGrpc.Timestamp approved = 3;</code>
   * @return Whether the approved field is set.
   */
  boolean hasApproved();
  /**
   * <code>.channelGrpc.Timestamp approved = 3;</code>
   * @return The approved.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.Timestamp getApproved();
  /**
   * <code>.channelGrpc.Timestamp approved = 3;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.TimestampOrBuilder getApprovedOrBuilder();

  /**
   * <code>.channelGrpc.Timestamp registrationCompleted = 4;</code>
   * @return Whether the registrationCompleted field is set.
   */
  boolean hasRegistrationCompleted();
  /**
   * <code>.channelGrpc.Timestamp registrationCompleted = 4;</code>
   * @return The registrationCompleted.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.Timestamp getRegistrationCompleted();
  /**
   * <code>.channelGrpc.Timestamp registrationCompleted = 4;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.TimestampOrBuilder getRegistrationCompletedOrBuilder();
}
