// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

/**
 * Protobuf type {@code channelGrpc.AgentProxyRequest}
 */
public final class AgentProxyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:channelGrpc.AgentProxyRequest)
    AgentProxyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgentProxyRequest.newBuilder() to construct.
  private AgentProxyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgentProxyRequest() {
    destIp_ = "";
    header_ = "";
    payload_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AgentProxyRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_AgentProxyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_AgentProxyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.class, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.Builder.class);
  }

  public static final int IDPROXYREQUEST_FIELD_NUMBER = 1;
  private long idProxyRequest_;
  /**
   * <code>int64 idProxyRequest = 1;</code>
   * @return The idProxyRequest.
   */
  @java.lang.Override
  public long getIdProxyRequest() {
    return idProxyRequest_;
  }

  public static final int AGENTSOURCE_FIELD_NUMBER = 2;
  private net.rossonet.ptalk.channel.protobuf.server.grpc.Agent agentSource_;
  /**
   * <code>.channelGrpc.Agent agentSource = 2;</code>
   * @return Whether the agentSource field is set.
   */
  @java.lang.Override
  public boolean hasAgentSource() {
    return agentSource_ != null;
  }
  /**
   * <code>.channelGrpc.Agent agentSource = 2;</code>
   * @return The agentSource.
   */
  @java.lang.Override
  public net.rossonet.ptalk.channel.protobuf.server.grpc.Agent getAgentSource() {
    return agentSource_ == null ? net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.getDefaultInstance() : agentSource_;
  }
  /**
   * <code>.channelGrpc.Agent agentSource = 2;</code>
   */
  @java.lang.Override
  public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder getAgentSourceOrBuilder() {
    return getAgentSource();
  }

  public static final int AGENTDESTINATION_FIELD_NUMBER = 3;
  private net.rossonet.ptalk.channel.protobuf.server.grpc.Agent agentDestination_;
  /**
   * <code>.channelGrpc.Agent agentDestination = 3;</code>
   * @return Whether the agentDestination field is set.
   */
  @java.lang.Override
  public boolean hasAgentDestination() {
    return agentDestination_ != null;
  }
  /**
   * <code>.channelGrpc.Agent agentDestination = 3;</code>
   * @return The agentDestination.
   */
  @java.lang.Override
  public net.rossonet.ptalk.channel.protobuf.server.grpc.Agent getAgentDestination() {
    return agentDestination_ == null ? net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.getDefaultInstance() : agentDestination_;
  }
  /**
   * <code>.channelGrpc.Agent agentDestination = 3;</code>
   */
  @java.lang.Override
  public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder getAgentDestinationOrBuilder() {
    return getAgentDestination();
  }

  public static final int DESTIP_FIELD_NUMBER = 4;
  private volatile java.lang.Object destIp_;
  /**
   * <code>string destIp = 4;</code>
   * @return The destIp.
   */
  @java.lang.Override
  public java.lang.String getDestIp() {
    java.lang.Object ref = destIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destIp_ = s;
      return s;
    }
  }
  /**
   * <code>string destIp = 4;</code>
   * @return The bytes for destIp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestIpBytes() {
    java.lang.Object ref = destIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTPORT_FIELD_NUMBER = 5;
  private int destPort_;
  /**
   * <code>int32 destPort = 5;</code>
   * @return The destPort.
   */
  @java.lang.Override
  public int getDestPort() {
    return destPort_;
  }

  public static final int HEADER_FIELD_NUMBER = 6;
  private volatile java.lang.Object header_;
  /**
   * <code>string header = 6;</code>
   * @return The header.
   */
  @java.lang.Override
  public java.lang.String getHeader() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      header_ = s;
      return s;
    }
  }
  /**
   * <code>string header = 6;</code>
   * @return The bytes for header.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeaderBytes() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      header_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 7;
  private volatile java.lang.Object payload_;
  /**
   * <code>string payload = 7;</code>
   * @return The payload.
   */
  @java.lang.Override
  public java.lang.String getPayload() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payload_ = s;
      return s;
    }
  }
  /**
   * <code>string payload = 7;</code>
   * @return The bytes for payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPayloadBytes() {
    java.lang.Object ref = payload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOCKETSOTIMEOUT_FIELD_NUMBER = 8;
  private int socketSoTimeout_;
  /**
   * <code>int32 socketSoTimeout = 8;</code>
   * @return The socketSoTimeout.
   */
  @java.lang.Override
  public int getSocketSoTimeout() {
    return socketSoTimeout_;
  }

  public static final int SOCKETTCPNODELAY_FIELD_NUMBER = 9;
  private boolean socketTcpNoDelay_;
  /**
   * <code>bool socketTcpNoDelay = 9;</code>
   * @return The socketTcpNoDelay.
   */
  @java.lang.Override
  public boolean getSocketTcpNoDelay() {
    return socketTcpNoDelay_;
  }

  public static final int SOCKETKEEPALIVE_FIELD_NUMBER = 10;
  private boolean socketKeepAlive_;
  /**
   * <code>bool socketKeepAlive = 10;</code>
   * @return The socketKeepAlive.
   */
  @java.lang.Override
  public boolean getSocketKeepAlive() {
    return socketKeepAlive_;
  }

  public static final int SOCKETRECEIVEBUFFERSIZE_FIELD_NUMBER = 11;
  private int socketReceiveBufferSize_;
  /**
   * <code>int32 socketReceiveBufferSize = 11;</code>
   * @return The socketReceiveBufferSize.
   */
  @java.lang.Override
  public int getSocketReceiveBufferSize() {
    return socketReceiveBufferSize_;
  }

  public static final int SOCKETREUSEADDRESS_FIELD_NUMBER = 12;
  private boolean socketReuseAddress_;
  /**
   * <code>bool socketReuseAddress = 12;</code>
   * @return The socketReuseAddress.
   */
  @java.lang.Override
  public boolean getSocketReuseAddress() {
    return socketReuseAddress_;
  }

  public static final int SOCKETTRAFFICCLASS_FIELD_NUMBER = 13;
  private int socketTrafficClass_;
  /**
   * <code>int32 socketTrafficClass = 13;</code>
   * @return The socketTrafficClass.
   */
  @java.lang.Override
  public int getSocketTrafficClass() {
    return socketTrafficClass_;
  }

  public static final int SOCKETQOS_FIELD_NUMBER = 14;
  private int socketQos_;
  /**
   * <code>int32 socketQos = 14;</code>
   * @return The socketQos.
   */
  @java.lang.Override
  public int getSocketQos() {
    return socketQos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idProxyRequest_ != 0L) {
      output.writeInt64(1, idProxyRequest_);
    }
    if (agentSource_ != null) {
      output.writeMessage(2, getAgentSource());
    }
    if (agentDestination_ != null) {
      output.writeMessage(3, getAgentDestination());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destIp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destIp_);
    }
    if (destPort_ != 0) {
      output.writeInt32(5, destPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(header_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, header_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(payload_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, payload_);
    }
    if (socketSoTimeout_ != 0) {
      output.writeInt32(8, socketSoTimeout_);
    }
    if (socketTcpNoDelay_ != false) {
      output.writeBool(9, socketTcpNoDelay_);
    }
    if (socketKeepAlive_ != false) {
      output.writeBool(10, socketKeepAlive_);
    }
    if (socketReceiveBufferSize_ != 0) {
      output.writeInt32(11, socketReceiveBufferSize_);
    }
    if (socketReuseAddress_ != false) {
      output.writeBool(12, socketReuseAddress_);
    }
    if (socketTrafficClass_ != 0) {
      output.writeInt32(13, socketTrafficClass_);
    }
    if (socketQos_ != 0) {
      output.writeInt32(14, socketQos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idProxyRequest_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, idProxyRequest_);
    }
    if (agentSource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAgentSource());
    }
    if (agentDestination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAgentDestination());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destIp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destIp_);
    }
    if (destPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, destPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(header_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, header_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(payload_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, payload_);
    }
    if (socketSoTimeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, socketSoTimeout_);
    }
    if (socketTcpNoDelay_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, socketTcpNoDelay_);
    }
    if (socketKeepAlive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, socketKeepAlive_);
    }
    if (socketReceiveBufferSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, socketReceiveBufferSize_);
    }
    if (socketReuseAddress_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, socketReuseAddress_);
    }
    if (socketTrafficClass_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, socketTrafficClass_);
    }
    if (socketQos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, socketQos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest)) {
      return super.equals(obj);
    }
    net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest other = (net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest) obj;

    if (getIdProxyRequest()
        != other.getIdProxyRequest()) return false;
    if (hasAgentSource() != other.hasAgentSource()) return false;
    if (hasAgentSource()) {
      if (!getAgentSource()
          .equals(other.getAgentSource())) return false;
    }
    if (hasAgentDestination() != other.hasAgentDestination()) return false;
    if (hasAgentDestination()) {
      if (!getAgentDestination()
          .equals(other.getAgentDestination())) return false;
    }
    if (!getDestIp()
        .equals(other.getDestIp())) return false;
    if (getDestPort()
        != other.getDestPort()) return false;
    if (!getHeader()
        .equals(other.getHeader())) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getSocketSoTimeout()
        != other.getSocketSoTimeout()) return false;
    if (getSocketTcpNoDelay()
        != other.getSocketTcpNoDelay()) return false;
    if (getSocketKeepAlive()
        != other.getSocketKeepAlive()) return false;
    if (getSocketReceiveBufferSize()
        != other.getSocketReceiveBufferSize()) return false;
    if (getSocketReuseAddress()
        != other.getSocketReuseAddress()) return false;
    if (getSocketTrafficClass()
        != other.getSocketTrafficClass()) return false;
    if (getSocketQos()
        != other.getSocketQos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDPROXYREQUEST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdProxyRequest());
    if (hasAgentSource()) {
      hash = (37 * hash) + AGENTSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getAgentSource().hashCode();
    }
    if (hasAgentDestination()) {
      hash = (37 * hash) + AGENTDESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getAgentDestination().hashCode();
    }
    hash = (37 * hash) + DESTIP_FIELD_NUMBER;
    hash = (53 * hash) + getDestIp().hashCode();
    hash = (37 * hash) + DESTPORT_FIELD_NUMBER;
    hash = (53 * hash) + getDestPort();
    hash = (37 * hash) + HEADER_FIELD_NUMBER;
    hash = (53 * hash) + getHeader().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + SOCKETSOTIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getSocketSoTimeout();
    hash = (37 * hash) + SOCKETTCPNODELAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSocketTcpNoDelay());
    hash = (37 * hash) + SOCKETKEEPALIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSocketKeepAlive());
    hash = (37 * hash) + SOCKETRECEIVEBUFFERSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSocketReceiveBufferSize();
    hash = (37 * hash) + SOCKETREUSEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSocketReuseAddress());
    hash = (37 * hash) + SOCKETTRAFFICCLASS_FIELD_NUMBER;
    hash = (53 * hash) + getSocketTrafficClass();
    hash = (37 * hash) + SOCKETQOS_FIELD_NUMBER;
    hash = (53 * hash) + getSocketQos();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code channelGrpc.AgentProxyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:channelGrpc.AgentProxyRequest)
      net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_AgentProxyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_AgentProxyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.class, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.Builder.class);
    }

    // Construct using net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idProxyRequest_ = 0L;

      if (agentSourceBuilder_ == null) {
        agentSource_ = null;
      } else {
        agentSource_ = null;
        agentSourceBuilder_ = null;
      }
      if (agentDestinationBuilder_ == null) {
        agentDestination_ = null;
      } else {
        agentDestination_ = null;
        agentDestinationBuilder_ = null;
      }
      destIp_ = "";

      destPort_ = 0;

      header_ = "";

      payload_ = "";

      socketSoTimeout_ = 0;

      socketTcpNoDelay_ = false;

      socketKeepAlive_ = false;

      socketReceiveBufferSize_ = 0;

      socketReuseAddress_ = false;

      socketTrafficClass_ = 0;

      socketQos_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_AgentProxyRequest_descriptor;
    }

    @java.lang.Override
    public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest getDefaultInstanceForType() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest build() {
      net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest buildPartial() {
      net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest result = new net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest(this);
      result.idProxyRequest_ = idProxyRequest_;
      if (agentSourceBuilder_ == null) {
        result.agentSource_ = agentSource_;
      } else {
        result.agentSource_ = agentSourceBuilder_.build();
      }
      if (agentDestinationBuilder_ == null) {
        result.agentDestination_ = agentDestination_;
      } else {
        result.agentDestination_ = agentDestinationBuilder_.build();
      }
      result.destIp_ = destIp_;
      result.destPort_ = destPort_;
      result.header_ = header_;
      result.payload_ = payload_;
      result.socketSoTimeout_ = socketSoTimeout_;
      result.socketTcpNoDelay_ = socketTcpNoDelay_;
      result.socketKeepAlive_ = socketKeepAlive_;
      result.socketReceiveBufferSize_ = socketReceiveBufferSize_;
      result.socketReuseAddress_ = socketReuseAddress_;
      result.socketTrafficClass_ = socketTrafficClass_;
      result.socketQos_ = socketQos_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest) {
        return mergeFrom((net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest other) {
      if (other == net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest.getDefaultInstance()) return this;
      if (other.getIdProxyRequest() != 0L) {
        setIdProxyRequest(other.getIdProxyRequest());
      }
      if (other.hasAgentSource()) {
        mergeAgentSource(other.getAgentSource());
      }
      if (other.hasAgentDestination()) {
        mergeAgentDestination(other.getAgentDestination());
      }
      if (!other.getDestIp().isEmpty()) {
        destIp_ = other.destIp_;
        onChanged();
      }
      if (other.getDestPort() != 0) {
        setDestPort(other.getDestPort());
      }
      if (!other.getHeader().isEmpty()) {
        header_ = other.header_;
        onChanged();
      }
      if (!other.getPayload().isEmpty()) {
        payload_ = other.payload_;
        onChanged();
      }
      if (other.getSocketSoTimeout() != 0) {
        setSocketSoTimeout(other.getSocketSoTimeout());
      }
      if (other.getSocketTcpNoDelay() != false) {
        setSocketTcpNoDelay(other.getSocketTcpNoDelay());
      }
      if (other.getSocketKeepAlive() != false) {
        setSocketKeepAlive(other.getSocketKeepAlive());
      }
      if (other.getSocketReceiveBufferSize() != 0) {
        setSocketReceiveBufferSize(other.getSocketReceiveBufferSize());
      }
      if (other.getSocketReuseAddress() != false) {
        setSocketReuseAddress(other.getSocketReuseAddress());
      }
      if (other.getSocketTrafficClass() != 0) {
        setSocketTrafficClass(other.getSocketTrafficClass());
      }
      if (other.getSocketQos() != 0) {
        setSocketQos(other.getSocketQos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              idProxyRequest_ = input.readInt64();

              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getAgentSourceFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAgentDestinationFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            case 34: {
              destIp_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 40: {
              destPort_ = input.readInt32();

              break;
            } // case 40
            case 50: {
              header_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              payload_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 64: {
              socketSoTimeout_ = input.readInt32();

              break;
            } // case 64
            case 72: {
              socketTcpNoDelay_ = input.readBool();

              break;
            } // case 72
            case 80: {
              socketKeepAlive_ = input.readBool();

              break;
            } // case 80
            case 88: {
              socketReceiveBufferSize_ = input.readInt32();

              break;
            } // case 88
            case 96: {
              socketReuseAddress_ = input.readBool();

              break;
            } // case 96
            case 104: {
              socketTrafficClass_ = input.readInt32();

              break;
            } // case 104
            case 112: {
              socketQos_ = input.readInt32();

              break;
            } // case 112
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long idProxyRequest_ ;
    /**
     * <code>int64 idProxyRequest = 1;</code>
     * @return The idProxyRequest.
     */
    @java.lang.Override
    public long getIdProxyRequest() {
      return idProxyRequest_;
    }
    /**
     * <code>int64 idProxyRequest = 1;</code>
     * @param value The idProxyRequest to set.
     * @return This builder for chaining.
     */
    public Builder setIdProxyRequest(long value) {
      
      idProxyRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idProxyRequest = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdProxyRequest() {
      
      idProxyRequest_ = 0L;
      onChanged();
      return this;
    }

    private net.rossonet.ptalk.channel.protobuf.server.grpc.Agent agentSource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.rossonet.ptalk.channel.protobuf.server.grpc.Agent, net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder> agentSourceBuilder_;
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     * @return Whether the agentSource field is set.
     */
    public boolean hasAgentSource() {
      return agentSourceBuilder_ != null || agentSource_ != null;
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     * @return The agentSource.
     */
    public net.rossonet.ptalk.channel.protobuf.server.grpc.Agent getAgentSource() {
      if (agentSourceBuilder_ == null) {
        return agentSource_ == null ? net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.getDefaultInstance() : agentSource_;
      } else {
        return agentSourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    public Builder setAgentSource(net.rossonet.ptalk.channel.protobuf.server.grpc.Agent value) {
      if (agentSourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        agentSource_ = value;
        onChanged();
      } else {
        agentSourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    public Builder setAgentSource(
        net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder builderForValue) {
      if (agentSourceBuilder_ == null) {
        agentSource_ = builderForValue.build();
        onChanged();
      } else {
        agentSourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    public Builder mergeAgentSource(net.rossonet.ptalk.channel.protobuf.server.grpc.Agent value) {
      if (agentSourceBuilder_ == null) {
        if (agentSource_ != null) {
          agentSource_ =
            net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.newBuilder(agentSource_).mergeFrom(value).buildPartial();
        } else {
          agentSource_ = value;
        }
        onChanged();
      } else {
        agentSourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    public Builder clearAgentSource() {
      if (agentSourceBuilder_ == null) {
        agentSource_ = null;
        onChanged();
      } else {
        agentSource_ = null;
        agentSourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    public net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder getAgentSourceBuilder() {
      
      onChanged();
      return getAgentSourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder getAgentSourceOrBuilder() {
      if (agentSourceBuilder_ != null) {
        return agentSourceBuilder_.getMessageOrBuilder();
      } else {
        return agentSource_ == null ?
            net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.getDefaultInstance() : agentSource_;
      }
    }
    /**
     * <code>.channelGrpc.Agent agentSource = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.rossonet.ptalk.channel.protobuf.server.grpc.Agent, net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder> 
        getAgentSourceFieldBuilder() {
      if (agentSourceBuilder_ == null) {
        agentSourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.rossonet.ptalk.channel.protobuf.server.grpc.Agent, net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder>(
                getAgentSource(),
                getParentForChildren(),
                isClean());
        agentSource_ = null;
      }
      return agentSourceBuilder_;
    }

    private net.rossonet.ptalk.channel.protobuf.server.grpc.Agent agentDestination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.rossonet.ptalk.channel.protobuf.server.grpc.Agent, net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder> agentDestinationBuilder_;
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     * @return Whether the agentDestination field is set.
     */
    public boolean hasAgentDestination() {
      return agentDestinationBuilder_ != null || agentDestination_ != null;
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     * @return The agentDestination.
     */
    public net.rossonet.ptalk.channel.protobuf.server.grpc.Agent getAgentDestination() {
      if (agentDestinationBuilder_ == null) {
        return agentDestination_ == null ? net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.getDefaultInstance() : agentDestination_;
      } else {
        return agentDestinationBuilder_.getMessage();
      }
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    public Builder setAgentDestination(net.rossonet.ptalk.channel.protobuf.server.grpc.Agent value) {
      if (agentDestinationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        agentDestination_ = value;
        onChanged();
      } else {
        agentDestinationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    public Builder setAgentDestination(
        net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder builderForValue) {
      if (agentDestinationBuilder_ == null) {
        agentDestination_ = builderForValue.build();
        onChanged();
      } else {
        agentDestinationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    public Builder mergeAgentDestination(net.rossonet.ptalk.channel.protobuf.server.grpc.Agent value) {
      if (agentDestinationBuilder_ == null) {
        if (agentDestination_ != null) {
          agentDestination_ =
            net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.newBuilder(agentDestination_).mergeFrom(value).buildPartial();
        } else {
          agentDestination_ = value;
        }
        onChanged();
      } else {
        agentDestinationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    public Builder clearAgentDestination() {
      if (agentDestinationBuilder_ == null) {
        agentDestination_ = null;
        onChanged();
      } else {
        agentDestination_ = null;
        agentDestinationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    public net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder getAgentDestinationBuilder() {
      
      onChanged();
      return getAgentDestinationFieldBuilder().getBuilder();
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder getAgentDestinationOrBuilder() {
      if (agentDestinationBuilder_ != null) {
        return agentDestinationBuilder_.getMessageOrBuilder();
      } else {
        return agentDestination_ == null ?
            net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.getDefaultInstance() : agentDestination_;
      }
    }
    /**
     * <code>.channelGrpc.Agent agentDestination = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.rossonet.ptalk.channel.protobuf.server.grpc.Agent, net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder> 
        getAgentDestinationFieldBuilder() {
      if (agentDestinationBuilder_ == null) {
        agentDestinationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.rossonet.ptalk.channel.protobuf.server.grpc.Agent, net.rossonet.ptalk.channel.protobuf.server.grpc.Agent.Builder, net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder>(
                getAgentDestination(),
                getParentForChildren(),
                isClean());
        agentDestination_ = null;
      }
      return agentDestinationBuilder_;
    }

    private java.lang.Object destIp_ = "";
    /**
     * <code>string destIp = 4;</code>
     * @return The destIp.
     */
    public java.lang.String getDestIp() {
      java.lang.Object ref = destIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destIp = 4;</code>
     * @return The bytes for destIp.
     */
    public com.google.protobuf.ByteString
        getDestIpBytes() {
      java.lang.Object ref = destIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destIp = 4;</code>
     * @param value The destIp to set.
     * @return This builder for chaining.
     */
    public Builder setDestIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destIp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestIp() {
      
      destIp_ = getDefaultInstance().getDestIp();
      onChanged();
      return this;
    }
    /**
     * <code>string destIp = 4;</code>
     * @param value The bytes for destIp to set.
     * @return This builder for chaining.
     */
    public Builder setDestIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destIp_ = value;
      onChanged();
      return this;
    }

    private int destPort_ ;
    /**
     * <code>int32 destPort = 5;</code>
     * @return The destPort.
     */
    @java.lang.Override
    public int getDestPort() {
      return destPort_;
    }
    /**
     * <code>int32 destPort = 5;</code>
     * @param value The destPort to set.
     * @return This builder for chaining.
     */
    public Builder setDestPort(int value) {
      
      destPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 destPort = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestPort() {
      
      destPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object header_ = "";
    /**
     * <code>string header = 6;</code>
     * @return The header.
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        header_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string header = 6;</code>
     * @return The bytes for header.
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string header = 6;</code>
     * @param value The header to set.
     * @return This builder for chaining.
     */
    public Builder setHeader(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      header_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string header = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeader() {
      
      header_ = getDefaultInstance().getHeader();
      onChanged();
      return this;
    }
    /**
     * <code>string header = 6;</code>
     * @param value The bytes for header to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      header_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object payload_ = "";
    /**
     * <code>string payload = 7;</code>
     * @return The payload.
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string payload = 7;</code>
     * @return The bytes for payload.
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payload = 7;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string payload = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }
    /**
     * <code>string payload = 7;</code>
     * @param value The bytes for payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      payload_ = value;
      onChanged();
      return this;
    }

    private int socketSoTimeout_ ;
    /**
     * <code>int32 socketSoTimeout = 8;</code>
     * @return The socketSoTimeout.
     */
    @java.lang.Override
    public int getSocketSoTimeout() {
      return socketSoTimeout_;
    }
    /**
     * <code>int32 socketSoTimeout = 8;</code>
     * @param value The socketSoTimeout to set.
     * @return This builder for chaining.
     */
    public Builder setSocketSoTimeout(int value) {
      
      socketSoTimeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 socketSoTimeout = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketSoTimeout() {
      
      socketSoTimeout_ = 0;
      onChanged();
      return this;
    }

    private boolean socketTcpNoDelay_ ;
    /**
     * <code>bool socketTcpNoDelay = 9;</code>
     * @return The socketTcpNoDelay.
     */
    @java.lang.Override
    public boolean getSocketTcpNoDelay() {
      return socketTcpNoDelay_;
    }
    /**
     * <code>bool socketTcpNoDelay = 9;</code>
     * @param value The socketTcpNoDelay to set.
     * @return This builder for chaining.
     */
    public Builder setSocketTcpNoDelay(boolean value) {
      
      socketTcpNoDelay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool socketTcpNoDelay = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketTcpNoDelay() {
      
      socketTcpNoDelay_ = false;
      onChanged();
      return this;
    }

    private boolean socketKeepAlive_ ;
    /**
     * <code>bool socketKeepAlive = 10;</code>
     * @return The socketKeepAlive.
     */
    @java.lang.Override
    public boolean getSocketKeepAlive() {
      return socketKeepAlive_;
    }
    /**
     * <code>bool socketKeepAlive = 10;</code>
     * @param value The socketKeepAlive to set.
     * @return This builder for chaining.
     */
    public Builder setSocketKeepAlive(boolean value) {
      
      socketKeepAlive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool socketKeepAlive = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketKeepAlive() {
      
      socketKeepAlive_ = false;
      onChanged();
      return this;
    }

    private int socketReceiveBufferSize_ ;
    /**
     * <code>int32 socketReceiveBufferSize = 11;</code>
     * @return The socketReceiveBufferSize.
     */
    @java.lang.Override
    public int getSocketReceiveBufferSize() {
      return socketReceiveBufferSize_;
    }
    /**
     * <code>int32 socketReceiveBufferSize = 11;</code>
     * @param value The socketReceiveBufferSize to set.
     * @return This builder for chaining.
     */
    public Builder setSocketReceiveBufferSize(int value) {
      
      socketReceiveBufferSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 socketReceiveBufferSize = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketReceiveBufferSize() {
      
      socketReceiveBufferSize_ = 0;
      onChanged();
      return this;
    }

    private boolean socketReuseAddress_ ;
    /**
     * <code>bool socketReuseAddress = 12;</code>
     * @return The socketReuseAddress.
     */
    @java.lang.Override
    public boolean getSocketReuseAddress() {
      return socketReuseAddress_;
    }
    /**
     * <code>bool socketReuseAddress = 12;</code>
     * @param value The socketReuseAddress to set.
     * @return This builder for chaining.
     */
    public Builder setSocketReuseAddress(boolean value) {
      
      socketReuseAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool socketReuseAddress = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketReuseAddress() {
      
      socketReuseAddress_ = false;
      onChanged();
      return this;
    }

    private int socketTrafficClass_ ;
    /**
     * <code>int32 socketTrafficClass = 13;</code>
     * @return The socketTrafficClass.
     */
    @java.lang.Override
    public int getSocketTrafficClass() {
      return socketTrafficClass_;
    }
    /**
     * <code>int32 socketTrafficClass = 13;</code>
     * @param value The socketTrafficClass to set.
     * @return This builder for chaining.
     */
    public Builder setSocketTrafficClass(int value) {
      
      socketTrafficClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 socketTrafficClass = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketTrafficClass() {
      
      socketTrafficClass_ = 0;
      onChanged();
      return this;
    }

    private int socketQos_ ;
    /**
     * <code>int32 socketQos = 14;</code>
     * @return The socketQos.
     */
    @java.lang.Override
    public int getSocketQos() {
      return socketQos_;
    }
    /**
     * <code>int32 socketQos = 14;</code>
     * @param value The socketQos to set.
     * @return This builder for chaining.
     */
    public Builder setSocketQos(int value) {
      
      socketQos_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 socketQos = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearSocketQos() {
      
      socketQos_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:channelGrpc.AgentProxyRequest)
  }

  // @@protoc_insertion_point(class_scope:channelGrpc.AgentProxyRequest)
  private static final net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest();
  }

  public static net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentProxyRequest>
      PARSER = new com.google.protobuf.AbstractParser<AgentProxyRequest>() {
    @java.lang.Override
    public AgentProxyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgentProxyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentProxyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rossonet.ptalk.channel.protobuf.server.grpc.AgentProxyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

