// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface ApproveAgentRequestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.ApproveAgentRequestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idRequest = 1;</code>
   * @return The idRequest.
   */
  java.lang.String getIdRequest();
  /**
   * <code>string idRequest = 1;</code>
   * @return The bytes for idRequest.
   */
  com.google.protobuf.ByteString
      getIdRequestBytes();

  /**
   * <code>string cert = 2;</code>
   * @return The cert.
   */
  java.lang.String getCert();
  /**
   * <code>string cert = 2;</code>
   * @return The bytes for cert.
   */
  com.google.protobuf.ByteString
      getCertBytes();

  /**
   * <code>string note = 3;</code>
   * @return The note.
   */
  java.lang.String getNote();
  /**
   * <code>string note = 3;</code>
   * @return The bytes for note.
   */
  com.google.protobuf.ByteString
      getNoteBytes();
}
