// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

/**
 * Protobuf type {@code channelGrpc.CompleteCommandReply}
 */
public final class CompleteCommandReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:channelGrpc.CompleteCommandReply)
    CompleteCommandReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompleteCommandReply.newBuilder() to construct.
  private CompleteCommandReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompleteCommandReply() {
    replies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompleteCommandReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_CompleteCommandReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_CompleteCommandReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.class, net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.Builder.class);
  }

  public static final int REPLIES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList replies_;
  /**
   * <code>repeated string replies = 1;</code>
   * @return A list containing the replies.
   */
  public com.google.protobuf.ProtocolStringList
      getRepliesList() {
    return replies_;
  }
  /**
   * <code>repeated string replies = 1;</code>
   * @return The count of replies.
   */
  public int getRepliesCount() {
    return replies_.size();
  }
  /**
   * <code>repeated string replies = 1;</code>
   * @param index The index of the element to return.
   * @return The replies at the given index.
   */
  public java.lang.String getReplies(int index) {
    return replies_.get(index);
  }
  /**
   * <code>repeated string replies = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the replies at the given index.
   */
  public com.google.protobuf.ByteString
      getRepliesBytes(int index) {
    return replies_.getByteString(index);
  }

  public static final int ERRORS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList errors_;
  /**
   * <code>repeated string errors = 2;</code>
   * @return A list containing the errors.
   */
  public com.google.protobuf.ProtocolStringList
      getErrorsList() {
    return errors_;
  }
  /**
   * <code>repeated string errors = 2;</code>
   * @return The count of errors.
   */
  public int getErrorsCount() {
    return errors_.size();
  }
  /**
   * <code>repeated string errors = 2;</code>
   * @param index The index of the element to return.
   * @return The errors at the given index.
   */
  public java.lang.String getErrors(int index) {
    return errors_.get(index);
  }
  /**
   * <code>repeated string errors = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the errors at the given index.
   */
  public com.google.protobuf.ByteString
      getErrorsBytes(int index) {
    return errors_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < replies_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, replies_.getRaw(i));
    }
    for (int i = 0; i < errors_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errors_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < replies_.size(); i++) {
        dataSize += computeStringSizeNoTag(replies_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRepliesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < errors_.size(); i++) {
        dataSize += computeStringSizeNoTag(errors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getErrorsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply)) {
      return super.equals(obj);
    }
    net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply other = (net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply) obj;

    if (!getRepliesList()
        .equals(other.getRepliesList())) return false;
    if (!getErrorsList()
        .equals(other.getErrorsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRepliesCount() > 0) {
      hash = (37 * hash) + REPLIES_FIELD_NUMBER;
      hash = (53 * hash) + getRepliesList().hashCode();
    }
    if (getErrorsCount() > 0) {
      hash = (37 * hash) + ERRORS_FIELD_NUMBER;
      hash = (53 * hash) + getErrorsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code channelGrpc.CompleteCommandReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:channelGrpc.CompleteCommandReply)
      net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_CompleteCommandReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_CompleteCommandReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.class, net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.Builder.class);
    }

    // Construct using net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      replies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.PtalkChannelGrpcServerGrpc.internal_static_channelGrpc_CompleteCommandReply_descriptor;
    }

    @java.lang.Override
    public net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply getDefaultInstanceForType() {
      return net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.getDefaultInstance();
    }

    @java.lang.Override
    public net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply build() {
      net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply buildPartial() {
      net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply result = new net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        replies_ = replies_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.replies_ = replies_;
      if (((bitField0_ & 0x00000002) != 0)) {
        errors_ = errors_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.errors_ = errors_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply) {
        return mergeFrom((net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply other) {
      if (other == net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply.getDefaultInstance()) return this;
      if (!other.replies_.isEmpty()) {
        if (replies_.isEmpty()) {
          replies_ = other.replies_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRepliesIsMutable();
          replies_.addAll(other.replies_);
        }
        onChanged();
      }
      if (!other.errors_.isEmpty()) {
        if (errors_.isEmpty()) {
          errors_ = other.errors_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureErrorsIsMutable();
          errors_.addAll(other.errors_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRepliesIsMutable();
              replies_.add(s);
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureErrorsIsMutable();
              errors_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList replies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRepliesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        replies_ = new com.google.protobuf.LazyStringArrayList(replies_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @return A list containing the replies.
     */
    public com.google.protobuf.ProtocolStringList
        getRepliesList() {
      return replies_.getUnmodifiableView();
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @return The count of replies.
     */
    public int getRepliesCount() {
      return replies_.size();
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @param index The index of the element to return.
     * @return The replies at the given index.
     */
    public java.lang.String getReplies(int index) {
      return replies_.get(index);
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the replies at the given index.
     */
    public com.google.protobuf.ByteString
        getRepliesBytes(int index) {
      return replies_.getByteString(index);
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @param index The index to set the value at.
     * @param value The replies to set.
     * @return This builder for chaining.
     */
    public Builder setReplies(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRepliesIsMutable();
      replies_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @param value The replies to add.
     * @return This builder for chaining.
     */
    public Builder addReplies(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRepliesIsMutable();
      replies_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @param values The replies to add.
     * @return This builder for chaining.
     */
    public Builder addAllReplies(
        java.lang.Iterable<java.lang.String> values) {
      ensureRepliesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, replies_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplies() {
      replies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string replies = 1;</code>
     * @param value The bytes of the replies to add.
     * @return This builder for chaining.
     */
    public Builder addRepliesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRepliesIsMutable();
      replies_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureErrorsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        errors_ = new com.google.protobuf.LazyStringArrayList(errors_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @return A list containing the errors.
     */
    public com.google.protobuf.ProtocolStringList
        getErrorsList() {
      return errors_.getUnmodifiableView();
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @return The count of errors.
     */
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @param index The index of the element to return.
     * @return The errors at the given index.
     */
    public java.lang.String getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the errors at the given index.
     */
    public com.google.protobuf.ByteString
        getErrorsBytes(int index) {
      return errors_.getByteString(index);
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @param index The index to set the value at.
     * @param value The errors to set.
     * @return This builder for chaining.
     */
    public Builder setErrors(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorsIsMutable();
      errors_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @param value The errors to add.
     * @return This builder for chaining.
     */
    public Builder addErrors(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorsIsMutable();
      errors_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @param values The errors to add.
     * @return This builder for chaining.
     */
    public Builder addAllErrors(
        java.lang.Iterable<java.lang.String> values) {
      ensureErrorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, errors_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrors() {
      errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string errors = 2;</code>
     * @param value The bytes of the errors to add.
     * @return This builder for chaining.
     */
    public Builder addErrorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureErrorsIsMutable();
      errors_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:channelGrpc.CompleteCommandReply)
  }

  // @@protoc_insertion_point(class_scope:channelGrpc.CompleteCommandReply)
  private static final net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply();
  }

  public static net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompleteCommandReply>
      PARSER = new com.google.protobuf.AbstractParser<CompleteCommandReply>() {
    @java.lang.Override
    public CompleteCommandReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompleteCommandReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompleteCommandReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rossonet.ptalk.channel.protobuf.server.grpc.CompleteCommandReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

