// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface ConfigReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.ConfigReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.channelGrpc.Agent agent = 1;</code>
   * @return Whether the agent field is set.
   */
  boolean hasAgent();
  /**
   * <code>.channelGrpc.Agent agent = 1;</code>
   * @return The agent.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.Agent getAgent();
  /**
   * <code>.channelGrpc.Agent agent = 1;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder getAgentOrBuilder();

  /**
   * <code>string base64Config = 2;</code>
   * @return The base64Config.
   */
  java.lang.String getBase64Config();
  /**
   * <code>string base64Config = 2;</code>
   * @return The bytes for base64Config.
   */
  com.google.protobuf.ByteString
      getBase64ConfigBytes();

  /**
   * <code>string jsonConfig = 3;</code>
   * @return The jsonConfig.
   */
  java.lang.String getJsonConfig();
  /**
   * <code>string jsonConfig = 3;</code>
   * @return The bytes for jsonConfig.
   */
  com.google.protobuf.ByteString
      getJsonConfigBytes();
}
