// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface MessageReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.MessageReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageReference = 1;</code>
   * @return The messageReference.
   */
  java.lang.String getMessageReference();
  /**
   * <code>string messageReference = 1;</code>
   * @return The bytes for messageReference.
   */
  com.google.protobuf.ByteString
      getMessageReferenceBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string UniqueName = 3;</code>
   * @return The uniqueName.
   */
  java.lang.String getUniqueName();
  /**
   * <code>string UniqueName = 3;</code>
   * @return The bytes for uniqueName.
   */
  com.google.protobuf.ByteString
      getUniqueNameBytes();

  /**
   * <code>string UniqueMessageId = 4;</code>
   * @return The uniqueMessageId.
   */
  java.lang.String getUniqueMessageId();
  /**
   * <code>string UniqueMessageId = 4;</code>
   * @return The bytes for uniqueMessageId.
   */
  com.google.protobuf.ByteString
      getUniqueMessageIdBytes();

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string messageReply = 7;</code>
   * @return The messageReply.
   */
  java.lang.String getMessageReply();
  /**
   * <code>string messageReply = 7;</code>
   * @return The bytes for messageReply.
   */
  com.google.protobuf.ByteString
      getMessageReplyBytes();

  /**
   * <code>repeated .channelGrpc.Parameter parameters = 8;</code>
   */
  java.util.List<net.rossonet.ptalk.channel.protobuf.server.grpc.Parameter> 
      getParametersList();
  /**
   * <code>repeated .channelGrpc.Parameter parameters = 8;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.Parameter getParameters(int index);
  /**
   * <code>repeated .channelGrpc.Parameter parameters = 8;</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .channelGrpc.Parameter parameters = 8;</code>
   */
  java.util.List<? extends net.rossonet.ptalk.channel.protobuf.server.grpc.ParameterOrBuilder> 
      getParametersOrBuilderList();
  /**
   * <code>repeated .channelGrpc.Parameter parameters = 8;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.ParameterOrBuilder getParametersOrBuilder(
      int index);

  /**
   * <code>string contextJson = 9;</code>
   * @return The contextJson.
   */
  java.lang.String getContextJson();
  /**
   * <code>string contextJson = 9;</code>
   * @return The bytes for contextJson.
   */
  com.google.protobuf.ByteString
      getContextJsonBytes();

  /**
   * <code>repeated .channelGrpc.Command commands = 10;</code>
   */
  java.util.List<net.rossonet.ptalk.channel.protobuf.server.grpc.Command> 
      getCommandsList();
  /**
   * <code>repeated .channelGrpc.Command commands = 10;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.Command getCommands(int index);
  /**
   * <code>repeated .channelGrpc.Command commands = 10;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .channelGrpc.Command commands = 10;</code>
   */
  java.util.List<? extends net.rossonet.ptalk.channel.protobuf.server.grpc.CommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .channelGrpc.Command commands = 10;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.CommandOrBuilder getCommandsOrBuilder(
      int index);
}
