// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface ParentScopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.ParentScope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scope = 1;</code>
   * @return The scope.
   */
  java.lang.String getScope();
  /**
   * <code>string scope = 1;</code>
   * @return The bytes for scope.
   */
  com.google.protobuf.ByteString
      getScopeBytes();

  /**
   * <code>.channelGrpc.NodeMetadata parent = 2;</code>
   * @return Whether the parent field is set.
   */
  boolean hasParent();
  /**
   * <code>.channelGrpc.NodeMetadata parent = 2;</code>
   * @return The parent.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.NodeMetadata getParent();
  /**
   * <code>.channelGrpc.NodeMetadata parent = 2;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.NodeMetadataOrBuilder getParentOrBuilder();
}
