// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface PollingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.PollingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.channelGrpc.Agent agent = 1;</code>
   * @return Whether the agent field is set.
   */
  boolean hasAgent();
  /**
   * <code>.channelGrpc.Agent agent = 1;</code>
   * @return The agent.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.Agent getAgent();
  /**
   * <code>.channelGrpc.Agent agent = 1;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.AgentOrBuilder getAgentOrBuilder();

  /**
   * <code>repeated .channelGrpc.DataNode dataNodes = 2;</code>
   */
  java.util.List<net.rossonet.ptalk.channel.protobuf.server.grpc.DataNode> 
      getDataNodesList();
  /**
   * <code>repeated .channelGrpc.DataNode dataNodes = 2;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.DataNode getDataNodes(int index);
  /**
   * <code>repeated .channelGrpc.DataNode dataNodes = 2;</code>
   */
  int getDataNodesCount();
  /**
   * <code>repeated .channelGrpc.DataNode dataNodes = 2;</code>
   */
  java.util.List<? extends net.rossonet.ptalk.channel.protobuf.server.grpc.DataNodeOrBuilder> 
      getDataNodesOrBuilderList();
  /**
   * <code>repeated .channelGrpc.DataNode dataNodes = 2;</code>
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.DataNodeOrBuilder getDataNodesOrBuilder(
      int index);
}
