// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptalk-channel-grpc.proto

package net.rossonet.ptalk.channel.protobuf.server.grpc;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:channelGrpc.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.channelGrpc.StatusValue status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.channelGrpc.StatusValue status = 1;</code>
   * @return The status.
   */
  net.rossonet.ptalk.channel.protobuf.server.grpc.StatusValue getStatus();
}
